import { initContract } from '@ts-rest/core';
import {
  reviewRoundSchema,
  reviewRoundListSchema,
  createReviewRoundSchema,
  updateReviewRoundSchema,
  reviewerInvitationSchema,
  reviewerInvitationListSchema,
  issueReviewerInvitationSchema,
  invitationTokenSchema,
  invitationActionResponseSchema,
  acceptPendingInvitationsResponseSchema,
  bidSchema,
  upsertBidSchema,
  bidListSchema,
  blindedPaperPoolSchema,
  coiListSchema,
  declareCoiSchema,
  conflictOfInterestSchema,
  assignmentListSchema,
  createAssignmentSchema,
  assignmentActionResponseSchema,
  copyAssignmentsFromPreviousRoundSchema,
  copyAssignmentsFromPreviousRoundResponseSchema,
  problemEnvelopeSchema,
  myAssignmentsSchema,
  reviewSchema,
  saveReviewSchema,
  submitReviewSchema,
  reviewActionResponseSchema,
  reviewListSchema,
  releaseReviewsSchema,
  releaseReviewsResponseSchema,
  rebuttalSchema,
  submitRebuttalSchema,
  rebuttalActionResponseSchema,
  rebuttalQuerySchema,
  decisionSchema,
  decisionListSchema,
  makeDecisionSchema,
  bulkDecisionSchema,
  notifyDecisionsSchema,
  decisionActionResponseSchema,
  bulkDecisionResponseSchema,
  notifyDecisionsResponseSchema,
  decisionQuerySchema,
  reviewRoundListQuerySchema,
  reviewerInvitationListQuerySchema,
  coiListQuerySchema,
  assignmentListQuerySchema,
  myAssignmentsQuerySchema,
  reviewListQuerySchema,
  cursorPaginationQuerySchema,
} from '@openconferences/schemas';
import { z } from 'zod';

const c = initContract();

const conferenceParams = z.object({
  conferenceId: z.string().uuid(),
});

const roundParams = z.object({
  conferenceId: z.string().uuid(),
  roundId: z.string().uuid(),
});

const paperParams = z.object({
  conferenceId: z.string().uuid(),
  paperId: z.string().uuid(),
});

const coiParams = z.object({
  conferenceId: z.string().uuid(),
  coiId: z.string().uuid(),
});

const assignmentParams = z.object({
  conferenceId: z.string().uuid(),
  assignmentId: z.string().uuid(),
});

const invitationParams = z.object({
  conferenceId: z.string().uuid(),
  invitationId: z.string().uuid(),
});

const bidListQuerySchema = cursorPaginationQuerySchema.extend({
  paperId: z.string().uuid().optional(),
  reviewerUserId: z.string().uuid().optional(),
});

const paperPoolQuerySchema = cursorPaginationQuerySchema;

export const reviewContract = c.router({
  listRounds: {
    method: 'GET',
    path: '/conferences/:conferenceId/rounds',
    pathParams: conferenceParams,
    query: reviewRoundListQuerySchema,
    responses: {
      200: reviewRoundListSchema,
      401: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'List review rounds for a conference',
  },
  createRound: {
    method: 'POST',
    path: '/conferences/:conferenceId/rounds',
    pathParams: conferenceParams,
    body: createReviewRoundSchema,
    responses: {
      201: reviewRoundSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Open a new review round',
  },
  updateRound: {
    method: 'PATCH',
    path: '/conferences/:conferenceId/rounds/:roundId',
    pathParams: roundParams,
    body: updateReviewRoundSchema,
    responses: {
      200: reviewRoundSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Update review round status or due dates',
  },
  listInvitations: {
    method: 'GET',
    path: '/conferences/:conferenceId/reviewer-invitations',
    pathParams: conferenceParams,
    query: reviewerInvitationListQuerySchema,
    responses: {
      200: reviewerInvitationListSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'List reviewer invitations (organizer)',
  },
  issueInvitation: {
    method: 'POST',
    path: '/conferences/:conferenceId/reviewer-invitations',
    pathParams: conferenceParams,
    body: issueReviewerInvitationSchema,
    responses: {
      201: reviewerInvitationSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Issue a reviewer invitation by email',
  },
  resendInvitation: {
    method: 'POST',
    path: '/conferences/:conferenceId/reviewer-invitations/:invitationId/resend',
    pathParams: invitationParams,
    body: c.noBody(),
    responses: {
      200: invitationActionResponseSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
      500: problemEnvelopeSchema,
    },
    summary: 'Resend the reviewer invitation email',
  },
  acceptInvitation: {
    method: 'POST',
    path: '/reviewer-invitations/accept',
    body: invitationTokenSchema,
    responses: {
      200: invitationActionResponseSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Accept a reviewer invitation by token',
  },
  acceptPendingInvitations: {
    method: 'POST',
    path: '/reviewer-invitations/accept-pending',
    body: c.noBody(),
    responses: {
      200: acceptPendingInvitationsResponseSchema,
      401: problemEnvelopeSchema,
    },
    summary: 'Accept all pending reviewer invitations for the signed-in user email',
  },
  declineInvitation: {
    method: 'POST',
    path: '/reviewer-invitations/decline',
    body: invitationTokenSchema,
    responses: {
      200: invitationActionResponseSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Decline a reviewer invitation by token',
  },
  listBids: {
    method: 'GET',
    path: '/conferences/:conferenceId/bids',
    pathParams: conferenceParams,
    query: bidListQuerySchema,
    responses: {
      200: bidListSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'List bids (organizer/chair view)',
  },
  getPaperPool: {
    method: 'GET',
    path: '/conferences/:conferenceId/review/paper-pool',
    pathParams: conferenceParams,
    query: paperPoolQuerySchema,
    responses: {
      200: blindedPaperPoolSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'Get blinded paper pool for reviewer bidding',
  },
  upsertBid: {
    method: 'PUT',
    path: '/conferences/:conferenceId/papers/:paperId/bids',
    pathParams: paperParams,
    body: upsertBidSchema,
    responses: {
      200: bidSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Upsert reviewer bid on a paper',
  },
  listCoi: {
    method: 'GET',
    path: '/conferences/:conferenceId/conflicts-of-interest',
    pathParams: conferenceParams,
    query: coiListQuerySchema,
    responses: {
      200: coiListSchema,
      401: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'List declared conflicts of interest',
  },
  declareCoi: {
    method: 'POST',
    path: '/conferences/:conferenceId/conflicts-of-interest',
    pathParams: conferenceParams,
    body: declareCoiSchema,
    responses: {
      201: conflictOfInterestSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'Declare a conflict of interest',
  },
  deleteCoi: {
    method: 'DELETE',
    path: '/conferences/:conferenceId/conflicts-of-interest/:coiId',
    pathParams: coiParams,
    body: c.noBody(),
    responses: {
      204: c.noBody(),
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'Remove a declared conflict of interest',
  },
  listAssignments: {
    method: 'GET',
    path: '/conferences/:conferenceId/rounds/:roundId/assignments',
    pathParams: roundParams,
    query: assignmentListQuerySchema,
    responses: {
      200: assignmentListSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'List reviewer assignments for a round',
  },
  copyAssignmentsFromPreviousRound: {
    method: 'POST',
    path: '/conferences/:conferenceId/rounds/:roundId/assignments/copy-from-previous-round',
    pathParams: roundParams,
    body: copyAssignmentsFromPreviousRoundSchema,
    responses: {
      200: copyAssignmentsFromPreviousRoundResponseSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Copy reviewer assignments from the previous review round',
  },
  createAssignment: {
    method: 'POST',
    path: '/conferences/:conferenceId/papers/:paperId/assignments',
    pathParams: paperParams,
    body: createAssignmentSchema,
    responses: {
      201: assignmentActionResponseSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Assign a reviewer to a paper (COI-checked)',
  },
  deleteAssignment: {
    method: 'DELETE',
    path: '/conferences/:conferenceId/assignments/:assignmentId',
    pathParams: assignmentParams,
    body: c.noBody(),
    responses: {
      204: c.noBody(),
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'Remove a reviewer assignment',
  },
  listMyAssignments: {
    method: 'GET',
    path: '/conferences/:conferenceId/review/my-assignments',
    pathParams: conferenceParams,
    query: myAssignmentsQuerySchema,
    responses: {
      200: myAssignmentsSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'List current reviewer assignments with review status',
  },
  getAssignmentReview: {
    method: 'GET',
    path: '/conferences/:conferenceId/assignments/:assignmentId/review',
    pathParams: assignmentParams,
    responses: {
      200: reviewSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'Get review for an assignment (reviewer only)',
  },
  saveAssignmentReview: {
    method: 'PUT',
    path: '/conferences/:conferenceId/assignments/:assignmentId/review',
    pathParams: assignmentParams,
    body: saveReviewSchema,
    responses: {
      200: reviewSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Save review draft (autosave)',
  },
  submitAssignmentReview: {
    method: 'POST',
    path: '/conferences/:conferenceId/assignments/:assignmentId/review/submit',
    pathParams: assignmentParams,
    body: submitReviewSchema,
    responses: {
      200: reviewActionResponseSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Submit a completed review',
  },
  listPaperReviews: {
    method: 'GET',
    path: '/conferences/:conferenceId/papers/:paperId/reviews',
    pathParams: paperParams,
    query: reviewListQuerySchema,
    responses: {
      200: reviewListSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'List reviews for a paper (visibility enforced)',
  },
  releaseReviews: {
    method: 'POST',
    path: '/conferences/:conferenceId/rounds/:roundId/reviews/release',
    pathParams: roundParams,
    body: releaseReviewsSchema,
    responses: {
      200: releaseReviewsResponseSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Release reviews to authors and open rebuttal window',
  },
  getRebuttal: {
    method: 'GET',
    path: '/conferences/:conferenceId/papers/:paperId/rebuttal',
    pathParams: paperParams,
    query: rebuttalQuerySchema,
    responses: {
      200: rebuttalSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'Get rebuttal for a paper (optional round filter)',
  },
  submitRebuttal: {
    method: 'POST',
    path: '/conferences/:conferenceId/papers/:paperId/rebuttal',
    pathParams: paperParams,
    body: submitRebuttalSchema,
    responses: {
      200: rebuttalActionResponseSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Submit author rebuttal for a paper',
  },
  listDecisions: {
    method: 'GET',
    path: '/conferences/:conferenceId/decisions',
    pathParams: conferenceParams,
    query: decisionQuerySchema,
    responses: {
      200: decisionListSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'List editorial decisions for a conference (chair/organizer)',
  },
  makeDecision: {
    method: 'POST',
    path: '/conferences/:conferenceId/papers/:paperId/decision',
    pathParams: paperParams,
    body: makeDecisionSchema,
    responses: {
      201: decisionActionResponseSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Record editorial decision for a paper in a round',
  },
  bulkDecide: {
    method: 'POST',
    path: '/conferences/:conferenceId/rounds/:roundId/decisions/bulk',
    pathParams: roundParams,
    body: bulkDecisionSchema,
    responses: {
      201: bulkDecisionResponseSchema,
      400: problemEnvelopeSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
      409: problemEnvelopeSchema,
    },
    summary: 'Bulk record editorial decisions for a round',
  },
  notifyDecisions: {
    method: 'POST',
    path: '/conferences/:conferenceId/rounds/:roundId/decisions/notify',
    pathParams: roundParams,
    body: notifyDecisionsSchema,
    responses: {
      200: notifyDecisionsResponseSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'Notify authors of decisions for a round',
  },
  getPaperDecision: {
    method: 'GET',
    path: '/conferences/:conferenceId/papers/:paperId/decision',
    pathParams: paperParams,
    query: decisionQuerySchema,
    responses: {
      200: decisionSchema,
      401: problemEnvelopeSchema,
      403: problemEnvelopeSchema,
      404: problemEnvelopeSchema,
    },
    summary: 'Get decision for a paper (author-visible after notification)',
  },
});

export type ReviewContract = typeof reviewContract;
